#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
imports:
    - { resource: admin/ }
easy_admin:
    design:
        form_theme: # Both themes are needed for ckeditor integration
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
    entities:
        Articles:
            class: App\Entity\Articles
        Sliders:
            class: App\Entity\Sliders
        Artistes:
            class: App\Entity\Artistes
        Categories:
            class: App\Entity\Categories
        Commentaires:
            class: App\Entity\Commentaires
        Expositions:
            class: App\Entity\Expositions
    user:
        name_property_path: 'username'
